// ═══════════════════════════════════════════════════════════════════
// EXTRA MOCK DATA for Outcomes, Governance, Guardrails, Story Map,
// Benefits, Fleet views. Exposes everything on window.
//
// All IDs and epics cross-reference the main EPICS[] array in the
// host script — keep these in sync when that shifts.
// ═══════════════════════════════════════════════════════════════════
(function () {

// ─── OUTCOMES (objectives & key results) ─────────────────────────
const OUTCOMES = [
  { id:"KR-01", objective:"Ship the adapter ecosystem without regressions",
    title:"Cut time-to-approve for new adapters",
    horizon:"now", status:"on-track",
    metric:"median hours from PR open → /dod passed",
    baseline:"38h", current:"21h", target:"≤ 16h",
    note:"Trending well — approval channels (e.p4.*) are the remaining lever. Two reviewers bottlenecked last sprint; mitigated by rotating duty roster.",
    epics:["e.p4.1","e.p4.2"], updated:"2026-04-14" },

  { id:"KR-02", objective:"Ship the adapter ecosystem without regressions",
    title:"Zero P1 regressions on GA adapters",
    horizon:"now", status:"met",
    metric:"P1 incidents in 30d",
    baseline:"2", current:"0", target:"0",
    note:"Held for three consecutive windows. Shadow-run harness caught a T3M1 regression before cut.",
    epics:["e.p3.1","e.p3.2"], updated:"2026-04-15" },

  { id:"KR-03", objective:"Harden governance for the skills platform",
    title:"100 % of dispatched skills carry signed manifest",
    horizon:"now", status:"on-track",
    metric:"% of runs verified against registry",
    baseline:"62 %", current:"94 %", target:"100 %",
    note:"Remaining 6 % are legacy adapters pending /improve cut — tracked in e.p3.3.",
    epics:["e.p3.2","e.p3.3"], updated:"2026-04-14" },

  { id:"KR-04", objective:"Harden governance for the skills platform",
    title:"Reduce manual policy review by half",
    horizon:"now", status:"at-risk",
    metric:"policy reviews touched by humans per week",
    baseline:"46", current:"38", target:"≤ 23",
    note:"Blocker B-01 (infra repo bootstrap) is the critical path — policy-as-code can't ship until the repo exists.",
    epics:["e.p3.3"], updated:"2026-04-13" },

  { id:"KR-05", objective:"Earn trust in benefit measurement",
    title:"Every shipped story links to a benefit metric",
    horizon:"next", status:"on-track",
    metric:"% of merged PRs with benefit-metric link",
    baseline:"31 %", current:"68 %", target:"≥ 90 %",
    note:"Telemetry watermarks (cycle-2) unblock the final 22 %. Data contracts signed off last week.",
    epics:["e.p5.1","e.p5.2"], updated:"2026-04-12" },

  { id:"KR-06", objective:"Earn trust in benefit measurement",
    title:"Counter-metrics defined for every benefit",
    horizon:"next", status:"on-track",
    metric:"benefit chains with a live counter-metric",
    baseline:"3 / 11", current:"8 / 11", target:"11 / 11",
    note:"Three chains still need a counter — tagged in the benefits view.",
    epics:["e.p5.1"], updated:"2026-04-14" },

  { id:"KR-07", objective:"Run agents safely in production",
    title:"Zero sandbox escapes in red-team exercises",
    horizon:"later", status:"nascent",
    metric:"successful escapes / 100 attempts",
    baseline:"—", current:"—", target:"0 / 100",
    note:"Discovery phase. Assumptions ASSUMPTIONS-01..03 open. Red-team partner scheduled for Q3.",
    epics:["e.p6.1"], updated:"2026-04-10" },

  { id:"KR-08", objective:"Run agents safely in production",
    title:"Isolate per-agent blast radius to its sandbox",
    horizon:"later", status:"nascent",
    metric:"% of skill calls running in per-agent namespace",
    baseline:"0 %", current:"0 %", target:"100 %",
    note:"Design spike this cycle — no implementation work yet.",
    epics:["e.p6.1"], updated:"2026-04-10" },

  { id:"KR-09", objective:"Operational excellence across the fleet",
    title:"p95 cycle lead-time",
    horizon:"now", status:"on-track",
    metric:"days from /discovery start → /dod passed",
    baseline:"38d", current:"29d", target:"≤ 25d",
    note:"Parallelising the inner loop cut 5 days. Next lever is gate automation.",
    epics:["e.p3.1","e.p4.1"], updated:"2026-04-15" },

  { id:"KR-10", objective:"Operational excellence across the fleet",
    title:"Blocker MTTR",
    horizon:"now", status:"off",
    metric:"median hours from blocker raised → cleared",
    baseline:"14h", current:"29h", target:"≤ 8h",
    note:"Regressed this sprint — B-01 and B-02 have been open 6 days. Need escalation path into platform-infra.",
    epics:["e.p3.3"], updated:"2026-04-15" },

  { id:"KR-11", objective:"Operational excellence across the fleet",
    title:"Definition-of-Ready completeness",
    horizon:"now", status:"met",
    metric:"% of stories entering /inner with all DoR artefacts",
    baseline:"78 %", current:"97 %", target:"≥ 95 %",
    note:"Holding comfortably. Credit: automated DoR checks in CI.",
    epics:["e.p3.1","e.p4.1"], updated:"2026-04-14" },
];

// ─── GATE CRITERIA per pipeline phase ────────────────────────────
const GATE_CRITERIA = [
  { phase:"discovery",  kind:"outer",   owner:"product lead",
    entry:["intent statement from portfolio brief","two candidate users named"],
    exit:["ASSUMPTIONS-01..N published","problem framing reviewed"],
    policy:"Floor: no phase-2 until assumptions are visible." },
  { phase:"benefit",    kind:"outer",   owner:"benefits owner",
    entry:["/discovery exit signed","initial metric candidates listed"],
    exit:["benefit metric + counter-metric specified","baseline captured"],
    policy:"Each metric MUST have a counter. Chains without one are rejected at /review." },
  { phase:"definition", kind:"outer",   owner:"epic owner",
    entry:["/benefit-metric exit signed"],
    exit:["epics scoped","stories sliced to ≤ 3d","NFRs named"],
    policy:"Stories larger than 3 person-days bounce back." },
  { phase:"review",     kind:"outer",   owner:"architecture council",
    entry:["/definition exit"],
    exit:["ADRs drafted","guardrails acknowledged"],
    policy:"Council quorum required. Async review allowed ≤ 48h." },
  { phase:"testplan",   kind:"outer",   owner:"test strategy",
    entry:["/review exit"],
    exit:["test strategy published","assurance budget set"],
    policy:"CI coverage floor enforced (see PF-02)." },
  { phase:"dor",        kind:"gate",    owner:"delivery lead",
    entry:["/test-plan signed"],
    exit:["DoR checklist passes 12/12"],
    policy:"HARD GATE — CI blocks dispatch without green DoR." },
  { phase:"dispatch",   kind:"outer",   owner:"delivery lead",
    entry:["DoR passed"],
    exit:["issues dispatched to /inner"],
    policy:"WIP limit per squad enforced by dispatch tool." },
  { phase:"inner",      kind:"inner",   owner:"engineer",
    entry:["issue claimed"],
    exit:["PR green against assurance suite"],
    policy:"TDD required. Red → green → refactor recorded in commit trailers." },
  { phase:"assurance",  kind:"gate",    owner:"CI bot",
    entry:["PR opened"],
    exit:["all checks green + 2 reviewers"],
    policy:"HARD GATE — merges blocked at CI level." },
  { phase:"dod",        kind:"outer",   owner:"epic owner",
    entry:["PR merged"],
    exit:["DoD checklist passes","telemetry confirms rollout"],
    policy:"DoD rolls up to benefit metric — see chain." },
  { phase:"trace",      kind:"outer",   owner:"benefits owner",
    entry:["DoD signed"],
    exit:["benefit attribution recorded","story → commit graph closed"],
    policy:"Trace artefact must exist for portfolio roll-up." },
  { phase:"improve",    kind:"improve", owner:"squad",
    entry:["trace closed"],
    exit:["retrospective committed","next-cycle asks logged"],
    policy:"Improve loop feeds phase-1 of next cycle." },
];

// ─── POLICY FLOORS (non-negotiable org minimums) ─────────────────
const POLICY_FLOORS = [
  { id:"PF-01", name:"Signed skills-manifest floor",
    scope:"every dispatched skill",
    version:"v2.3 · 2026-03-28",
    owner:"@security-council",
    details:"Dispatches are rejected at the adapter boundary unless the skill manifest hash matches the signed registry entry. Rotation procedure MUST preserve a 24h overlap.\n\nAudit events are kept ≥ 90 days." },
  { id:"PF-02", name:"Assurance coverage floor",
    scope:"every PR touching adapters",
    version:"v1.4 · 2026-02-11",
    owner:"@quality-council",
    details:"Adapter PRs must ship with unit tests covering ≥ 85% of changed lines AND one end-to-end shadow-run.\n\nCI enforces the floor; waivers require a named exception owner and auto-expire in 14 days." },
  { id:"PF-03", name:"Data-residency floor",
    scope:"every byte of user data",
    version:"v1.1 · 2025-12-02",
    owner:"@platform-infra",
    details:"User data at rest stays in its tenant region. Cross-region transit requires a named lawful-basis record AND is logged to the residency ledger.\n\nBreaches of this floor are P1 by definition." },
  { id:"PF-04", name:"Blast-radius floor",
    scope:"production agents",
    version:"draft · 2026-04-01",
    owner:"@runtime-team",
    details:"Production agents run in per-tenant sandboxes. Shared-fate resources (secrets, tokens, outbound network) are proxied through a deny-by-default broker.\n\nDraft: tightening once cycle-3 /discovery lands." },
  { id:"PF-05", name:"Rollback floor",
    scope:"every adapter release",
    version:"v1.0 · 2025-11-20",
    owner:"@platform-infra",
    details:"Any adapter shipped to GA must have a one-command rollback tested in staging within 7 days of release.\n\nAge-out alerts fire at T+6 days." },
  { id:"PF-06", name:"Human-in-the-loop floor",
    scope:"policy-review workflows",
    version:"v2.0 · 2026-01-08",
    owner:"@governance",
    details:"Changes to enforcement rules require ≥ 2 human reviewers, at least one outside the proposing squad.\n\nAutomated approvals are explicitly forbidden for this category." },
];

// ─── COMPLIANCE MATRIX (feature × framework) ─────────────────────
const COMPLIANCE_MATRIX = [
  { feature:"Skill registry signing", surface:"/platform/skills-framework",
    soc2:     { control:"CC7.2", status:"met",      artefact:"evidence/soc2/CC7.2-signing.md" },
    gdpr:     { control:"Art. 32", status:"met",     artefact:"evidence/gdpr/art32-integrity.md" },
    iso27001: { control:"A.8.28", status:"on-track", artefact:"evidence/iso/A.8.28-signing.md", note:"Audit scheduled Q2." },
    nistai:   { control:"GOVERN-1.4", status:"on-track", artefact:"evidence/nistai/govern-1.4.md" },
    t3m1:     { control:"T3M1-01", status:"met",     artefact:"evidence/t3m1/registry.md" },
  },
  { feature:"Tamper-evident audit log", surface:"/platform/telemetry",
    soc2:     { control:"CC7.2", status:"met",      artefact:"evidence/soc2/CC7.2-audit.md" },
    gdpr:     { control:"Art. 30", status:"met",    artefact:"evidence/gdpr/art30-records.md" },
    iso27001: { control:"A.8.15", status:"met",     artefact:"evidence/iso/A.8.15-logging.md" },
    nistai:   { control:"MEASURE-2.9", status:"on-track", artefact:"evidence/nistai/measure-2.9.md" },
    t3m1:     { control:"T3M1-02", status:"met",     artefact:"evidence/t3m1/audit.md" },
  },
  { feature:"Per-tenant sandbox", surface:"/runtime/agent-host",
    soc2:     { control:"CC6.6", status:"at-risk",  artefact:"evidence/soc2/CC6.6-sandbox.md", note:"Design pending cycle-3 /discovery." },
    gdpr:     { control:"Art. 32", status:"at-risk", artefact:"—" },
    iso27001: { control:"A.8.23", status:"at-risk", artefact:"—" },
    nistai:   { control:"MANAGE-2.3", status:"nascent", artefact:"draft — benefits tbd" },
    t3m1:     null,
  },
  { feature:"Data-residency enforcement", surface:"/platform/data-broker",
    soc2:     { control:"CC6.1", status:"met",      artefact:"evidence/soc2/CC6.1-residency.md" },
    gdpr:     { control:"Art. 44", status:"met",    artefact:"evidence/gdpr/art44-transfer.md" },
    iso27001: { control:"A.5.33", status:"met",     artefact:"evidence/iso/A.5.33-residency.md" },
    nistai:   null,
    t3m1:     { control:"T3M1-04", status:"met",    artefact:"evidence/t3m1/residency.md" },
  },
  { feature:"Approval channels for dispatch", surface:"/platform/approvals",
    soc2:     { control:"CC6.3", status:"on-track", artefact:"evidence/soc2/CC6.3-approvals.md" },
    gdpr:     null,
    iso27001: { control:"A.5.15", status:"on-track", artefact:"evidence/iso/A.5.15-access.md" },
    nistai:   { control:"GOVERN-2.1", status:"on-track", artefact:"evidence/nistai/govern-2.1.md" },
    t3m1:     { control:"T3M1-05", status:"on-track", artefact:"evidence/t3m1/approvals.md" },
  },
  { feature:"Benefit attribution / trace", surface:"/observability/trace",
    soc2:     null,
    gdpr:     null,
    iso27001: { control:"A.5.37", status:"on-track", artefact:"evidence/iso/A.5.37-process.md" },
    nistai:   { control:"MEASURE-3.2", status:"on-track", artefact:"evidence/nistai/measure-3.2.md" },
    t3m1:     { control:"T3M1-06", status:"on-track", artefact:"evidence/t3m1/trace.md" },
  },
  { feature:"Automated rollback", surface:"/platform/release-mgr",
    soc2:     { control:"CC7.3", status:"met",      artefact:"evidence/soc2/CC7.3-rollback.md" },
    gdpr:     null,
    iso27001: { control:"A.8.32", status:"met",     artefact:"evidence/iso/A.8.32-changes.md" },
    nistai:   null,
    t3m1:     { control:"T3M1-07", status:"met",    artefact:"evidence/t3m1/rollback.md" },
  },
  { feature:"Policy-as-code enforcement", surface:"/governance/opa",
    soc2:     { control:"CC5.3", status:"in-progress",  artefact:"—", note:"e.p3.3 unblocked but p3.3 PR #166 was empty (D8) — re-dispatch pending." },
    gdpr:     null,
    iso27001: { control:"A.5.31", status:"at-risk", artefact:"—" },
    nistai:   { control:"GOVERN-1.1", status:"at-risk", artefact:"draft" },
    t3m1:     null,
  },
];

// ─── GUARDRAILS REGISTRY ─────────────────────────────────────────
const GUARDRAILS = [
  { id:"MC-01", category:"mandatory-constraint",
    rule:"Every skill dispatched in production MUST hash-match the signed registry.",
    rationale:"Prevents silent drift and supply-chain substitution of skills. This is the root of T3M1.",
    enforcement:"Adapter boundary check + CI policy test. Violations are P1.",
    refs:["PF-01","T3M1-01"] },
  { id:"MC-02", category:"mandatory-constraint",
    rule:"No user data crosses a tenant-region boundary without a lawful-basis record.",
    rationale:"Data residency is a legal obligation and a user expectation.",
    enforcement:"Broker enforces at transit; residency ledger audited monthly.",
    refs:["PF-03","GDPR Art. 44"] },
  { id:"MC-03", category:"mandatory-constraint",
    rule:"Every benefit metric MUST declare a counter-metric.",
    rationale:"Single-metric optimisation creates blind spots. A counter forces discussion of trade-offs up front.",
    enforcement:"/review bounces chains without a counter back to /benefit-metric.",
    refs:["benefits chains"] },

  { id:"ADR-014", category:"adr",
    rule:"Use content-addressed manifests over name-based references.",
    rationale:"Hash-addressed manifests make tamper-evidence free and make cache invalidation a non-event.",
    enforcement:"Registry write path only accepts CAS manifests.",
    refs:["MC-01","e.p3.2"] },
  { id:"ADR-022", category:"adr",
    rule:"Approval channels are declarative, not imperative scripts.",
    rationale:"Declarative rules survive review, replay and audit better than one-off logic.",
    enforcement:"Rules authored in policy-DSL; imperative overrides logged as exceptions.",
    refs:["e.p4.1","PF-06"] },
  { id:"ADR-028", category:"adr",
    rule:"Benefit metrics live beside the code that emits them.",
    rationale:"Co-location keeps telemetry and business logic from drifting apart.",
    enforcement:"Lint rule — metrics declared outside a service directory fail CI.",
    refs:["KR-05","e.p5.1"] },

  { id:"PT-03", category:"pattern",
    rule:"Prefer idempotent dispatch over exactly-once delivery.",
    rationale:"Exactly-once is an illusion across tenants; idempotency handles retries cleanly.",
    enforcement:"Reviewer guidance; surfaced in /review checklist.",
    refs:["inner loop"] },
  { id:"PT-07", category:"pattern",
    rule:"Wrap external services with a declarative boundary.",
    rationale:"Isolates vendor-specific quirks from the rest of the codebase.",
    enforcement:"Pattern catalogue + /review encourages adoption.",
    refs:["adapter ecosystem"] },

  { id:"AP-02", category:"anti-pattern",
    rule:"Don't mutate manifest fields after signing — re-sign instead.",
    rationale:"In-place mutation breaks tamper-evidence without visible trace.",
    enforcement:"Reviewer education + linter catches common mutation patterns.",
    refs:["MC-01","ADR-014"] },
  { id:"AP-05", category:"anti-pattern",
    rule:"Avoid humans in the happy path of automated enforcement.",
    rationale:"Humans in the loop of every decision destroy throughput — reserve them for edges.",
    enforcement:"HITL allowed for escalations + policy changes only.",
    refs:["PF-06"] },
  { id:"AP-09", category:"anti-pattern",
    rule:"Don't ship a benefit metric you can't attribute to a commit.",
    rationale:"Un-traceable metrics create arguments, not alignment.",
    enforcement:"/trace phase rejects unlinked benefit claims.",
    refs:["KR-05","KR-06"] },

  { id:"NFR-01", category:"nfr",
    rule:"Adapter dispatch p95 latency stays under 220ms.",
    rationale:"Interactive UX depends on predictable low-tail dispatch.",
    enforcement:"SLO alert + automatic rollback at p95 > 280ms for 15min.",
    refs:["PF-05"] },
  { id:"NFR-04", category:"nfr",
    rule:"Availability ≥ 99.95 % for the adapter control plane.",
    rationale:"Control-plane outages pause every tenant — an ecosystem-wide blast radius.",
    enforcement:"Error-budget tracked weekly; budget burn pauses feature work.",
    refs:["fleet"] },
  { id:"NFR-09", category:"nfr",
    rule:"Cold-start for sandboxed agent < 1.4s p90.",
    rationale:"Perceived responsiveness of agent-first surfaces.",
    enforcement:"Benchmark harness on every release candidate.",
    refs:["cycle-3"] },

  { id:"CF-SOC2",   category:"compliance-framework",
    rule:"Maintain SOC 2 Type II across CC1–CC9 in audit scope.",
    rationale:"Customer contracts make SOC 2 table-stakes; lapse is a commercial risk.",
    enforcement:"Evidence auto-collected into /evidence/soc2/.",
    refs:["compliance matrix"] },
  { id:"CF-GDPR",   category:"compliance-framework",
    rule:"Honour GDPR lawful-basis + data-subject rights for all EU users.",
    rationale:"Statutory — not optional.",
    enforcement:"DPO sign-off on every schema change touching user data.",
    refs:["MC-02","PF-03"] },
  { id:"CF-NISTAI", category:"compliance-framework",
    rule:"Adopt NIST AI RMF GOVERN + MEASURE functions for agent workflows.",
    rationale:"Gives us a defensible, auditable posture as regulators arrive.",
    enforcement:"Quarterly RMF self-assessment.",
    refs:["cycle-3","KR-07"] },
];

// ─── STORY MAP THEMES ────────────────────────────────────────────
const STORY_THEMES = [
  { id:"theme.platform", name:"Platform hardening",
    epics: [
      { id:"se-01", linkEpicId:"e.p3.1", name:"Signed skill registry end-to-end",
        risk:"low",
        stories:[
          { id:"p3.1a", title:"Content-addressable manifest writer",
            state:"done", phase:"dod", acceptance:"manifest.sha is stable across rewrites" },
          { id:"p3.1b", title:"Registry read path verifies hash",
            state:"done", phase:"dod", acceptance:"unsigned dispatch rejected at boundary" },
          { id:"p3.1c", title:"Rotation overlap (24h) honoured",
            state:"done", phase:"dod", acceptance:"overlap window honoured during key roll" },
          { id:"p3.1d", title:"Audit events stream to evidence/",
            state:"done", phase:"dod", acceptance:"events available within 5s" },
          { id:"p3.1e", title:"Failure mode: registry down → fail closed",
            state:"done", phase:"dod", acceptance:"dispatch refuses rather than auto-allows" },
        ]},
      { id:"se-02", linkEpicId:"e.p3.2", name:"Tamper-evidence on audit stream",
        risk:"medium",
        stories:[
          { id:"p3.2a", title:"Merkle segment writer",
            state:"done", phase:"dod", acceptance:"root hash stable" },
          { id:"p3.2b", title:"Verifier service on cold storage",
            state:"current", phase:"dod", acceptance:"cold read path verifies in ≤ 2s" },
        ]},
      { id:"se-03", linkEpicId:"e.p3.3", name:"Platform-infra repo bootstrap",
        risk:"high",
        stories:[
          { id:"p3.3", title:"Bootstrap platform-infra repo",
            state:"blocked", phase:"dispatch",
            acceptance:"repo + CODEOWNERS + CI template merged",
            blocker:"D8: PR #166 merged empty — re-dispatch needed" },
          { id:"p3.4", title:"Define policy-as-code structure",
            state:"blocked", phase:"dor", blocker:"B-02",
            acceptance:"OPA bundle pipeline green" },
        ]},
    ]},

  { id:"theme.ecosystem", name:"Adapter ecosystem",
    epics: [
      { id:"se-04", linkEpicId:"e.p4.1", name:"Approval-channel primitives",
        risk:"medium",
        stories:[
          { id:"p4.1a", title:"Declarative rule engine",
            state:"current", phase:"inner", acceptance:"DSL parses + round-trips" },
          { id:"p4.1b", title:"Exception log with expiry",
            state:"current", phase:"inner", acceptance:"waivers auto-expire in 14 days" },
          { id:"p4.1c", title:"Review UI wiring",
            state:"review", phase:"inner", acceptance:"reviewer sees diff + policy impact" },
        ]},
      { id:"se-05", linkEpicId:"e.p4.2", name:"Third-party adapter SDK",
        risk:"low",
        stories:[
          { id:"p4.2a", title:"SDK scaffolding CLI",
            state:"done", phase:"dod", acceptance:"`sdk new` produces a buildable package" },
          { id:"p4.2b", title:"Versioned adapter contract tests",
            state:"current", phase:"inner", acceptance:"contract tests run in partner CI" },
        ]},
    ]},

  { id:"theme.telemetry", name:"Telemetry & benefits",
    epics:[
      { id:"se-06", linkEpicId:"e.p5.1", name:"Metric watermarks",
        risk:"medium",
        stories:[
          { id:"p5.1a", title:"Watermark protocol spec",
            state:"review", phase:"definition", acceptance:"RFC approved by data council" },
          { id:"p5.1b", title:"Emitter SDK for services",
            state:"current", phase:"definition", acceptance:"two pilot services emitting" },
          { id:"p5.1c", title:"Lagged metric back-fill", state:"done", phase:"dod",
            acceptance:"back-fill completes within cycle budget" },
        ]},
      { id:"se-07", linkEpicId:"e.p5.2", name:"Trace rollup for portfolio view",
        risk:"low",
        stories:[
          { id:"p5.2a", title:"Commit → story → metric graph builder",
            state:"current", phase:"definition", acceptance:"graph query <200ms on cycle window" },
        ]},
    ]},

  { id:"theme.runtime", name:"Runtime isolation",
    epics:[
      { id:"se-08", linkEpicId:"e.p6.1", name:"Per-agent sandbox",
        risk:"high",
        stories:[
          { id:"p6.1a", title:"Sandbox kernel spike",
            state:"current", phase:"discovery", acceptance:"prototype handles 3 agents" },
          { id:"p6.1b", title:"Secret broker deny-by-default",
            state:"current", phase:"discovery", acceptance:"no ambient creds reachable" },
        ]},
    ]},
];

// ─── BENEFIT CHAINS (hypothesis → metric → story → commit) ───────
const BENEFIT_CHAINS = [
  { id:"BC-01", name:"Signed registry cuts dispatch drift to zero",
    hypothesis:"If every dispatched skill hash-matches a signed registry entry, drift incidents drop to zero without a measurable throughput penalty.",
    counterStatus:"met",
    metrics:[
      { id:"M-drift", title:"Drift incidents per cycle",
        target:"0", current:"0", status:"met", source:"telemetry.drift" },
      { id:"M-disp",  title:"Dispatch latency p95",
        target:"≤ 220 ms", current:"198 ms", status:"on-track", source:"slo.dispatch" },
    ],
    stories:[
      { id:"p3.1a", title:"CAS manifest writer", state:"done" },
      { id:"p3.1b", title:"Verify on read", state:"done" },
      { id:"p3.1e", title:"Fail closed on registry outage", state:"done" },
    ],
    commits:[
      { sha:"a14fe9c", title:"feat(registry): content-address manifests", author:"@avery-k", date:"2026-04-08" },
      { sha:"71b3f02", title:"feat(boundary): reject unsigned dispatch", author:"@kai-m",  date:"2026-04-10" },
      { sha:"9d7cc41", title:"test(rotation): 24h overlap honoured",     author:"@avery-k", date:"2026-04-12" },
    ]},

  { id:"BC-02", name:"Approval channels halve reviewer load",
    hypothesis:"Declarative approval channels will cut reviewer load per PR by half without increasing defect escape rate.",
    counterStatus:"on-track",
    metrics:[
      { id:"M-rev",    title:"Reviewer touches per PR",
        target:"≤ 1.8", current:"2.4", status:"at-risk", source:"github.review" },
      { id:"M-escape", title:"Defect escape rate",
        target:"≤ 0.4 %", current:"0.3 %", status:"on-track", source:"incidents.defects" },
    ],
    stories:[
      { id:"p4.1a", title:"Declarative rule engine", state:"current" },
      { id:"p4.1b", title:"Exception log", state:"current" },
      { id:"p4.1c", title:"Review UI wiring", state:"current" },
    ],
    commits:[
      { sha:"33c0ab2", title:"feat(approvals): rule DSL parser", author:"@nori-w", date:"2026-04-13" },
    ]},

  { id:"BC-03", name:"Metric watermarks unlock trustworthy trace",
    hypothesis:"Watermarked metric streams will let us attribute ≥ 90 % of merged PRs to a benefit within 48h of merge.",
    counterStatus:"pending",
    metrics:[
      { id:"M-attrib", title:"PRs attributed to a benefit",
        target:"≥ 90 %", current:"68 %", status:"on-track", source:"trace.attribution" },
      { id:"M-latency",title:"Attribution latency",
        target:"≤ 48 h", current:"62 h", status:"at-risk", source:"trace.latency" },
    ],
    stories:[
      { id:"p5.1a", title:"Watermark protocol spec", state:"current" },
      { id:"p5.1b", title:"Emitter SDK", state:"current" },
    ],
    commits:[] },

  { id:"BC-04", name:"Tamper-evident audit earns the compliance win",
    hypothesis:"A Merkle-segmented audit stream will pass SOC 2 CC7.2 + ISO A.8.15 with no manual evidence gathering.",
    counterStatus:"met",
    metrics:[
      { id:"M-audit",  title:"Manual evidence hours per audit",
        target:"≤ 4 h", current:"3 h", status:"met", source:"evidence.manual" },
      { id:"M-verify", title:"Cold-read verification time",
        target:"≤ 2 s", current:"1.6 s", status:"met", source:"telemetry.verify" },
    ],
    stories:[
      { id:"p3.2a", title:"Merkle segment writer", state:"done" },
      { id:"p3.2b", title:"Verifier service", state:"current" },
    ],
    commits:[
      { sha:"f0a2d11", title:"feat(audit): merkle segments", author:"@priya-s", date:"2026-04-05" },
      { sha:"12aa7c9", title:"chore(audit): promote verifier", author:"@priya-s", date:"2026-04-11" },
    ]},
];

// ─── FLEET ROLL-UP ───────────────────────────────────────────────
const FLEET = [
  { id:"sq.platform", name:"Platform squad", lead:"@avery-k",
    repos:[
      { name:"platform/skills-framework", owner:"@avery-k",
        cycle:"Skills Platform · governance hardening", phase:"dod (phase 10)", phaseKey:"dod",
        storyCounts:{ done:18, current:2, blocked:0 }, loc:142_380, lastCommit:"14 min ago" },
      { name:"platform/registry", owner:"@avery-k",
        cycle:"Skills Platform · governance hardening", phase:"trace (phase 11)", phaseKey:"trace",
        storyCounts:{ done:11, current:1, blocked:0 }, loc:38_211, lastCommit:"1 h ago" },
      { name:"platform/approvals", owner:"@nori-w",
        cycle:"Adapter ecosystem · approval channels", phase:"inner (phase 8)", phaseKey:"inner",
        storyCounts:{ done:4, current:3, blocked:0 }, loc:21_004, lastCommit:"26 min ago" },
    ]},
  { id:"sq.telemetry", name:"Telemetry squad", lead:"@priya-s",
    repos:[
      { name:"platform/telemetry", owner:"@priya-s",
        cycle:"Skills Platform · governance hardening", phase:"dod (phase 10)", phaseKey:"dod",
        storyCounts:{ done:9, current:1, blocked:0 }, loc:54_902, lastCommit:"3 h ago" },
      { name:"platform/trace", owner:"@priya-s",
        cycle:"Telemetry · metric watermarks", phase:"definition (phase 3)", phaseKey:"definition",
        storyCounts:{ done:2, current:4, blocked:0 }, loc:12_441, lastCommit:"2 d ago" },
    ]},
  { id:"sq.infra", name:"Platform-infra squad", lead:"@kai-m",
    repos:[
      { name:"platform/platform-infra", owner:"@kai-m",
        cycle:"Skills Platform · governance hardening", phase:"dor (phase 6)", phaseKey:"dor",
        storyCounts:{ done:0, current:0, blocked:2 }, loc:4_112, lastCommit:"6 d ago" },
      { name:"platform/release-mgr", owner:"@kai-m",
        cycle:"Adapter ecosystem · approval channels", phase:"dod (phase 10)", phaseKey:"dod",
        storyCounts:{ done:7, current:1, blocked:0 }, loc:19_338, lastCommit:"1 d ago" },
    ]},
  { id:"sq.runtime", name:"Runtime squad", lead:"@jun-l",
    repos:[
      { name:"runtime/agent-host", owner:"@jun-l",
        cycle:"Runtime isolation · agent sandboxing", phase:"discovery (phase 1)", phaseKey:"discovery",
        storyCounts:{ done:0, current:2, blocked:0 }, loc:8_720, lastCommit:"11 h ago" },
      { name:"runtime/secret-broker", owner:"@jun-l",
        cycle:"Runtime isolation · agent sandboxing", phase:"discovery (phase 1)", phaseKey:"discovery",
        storyCounts:{ done:0, current:1, blocked:0 }, loc:3_104, lastCommit:"2 d ago" },
    ]},
  { id:"sq.sdk", name:"Partner SDK squad", lead:"@nori-w",
    repos:[
      { name:"platform/adapter-sdk", owner:"@nori-w",
        cycle:"Adapter ecosystem · approval channels", phase:"inner (phase 8)", phaseKey:"inner",
        storyCounts:{ done:6, current:1, blocked:0 }, loc:28_550, lastCommit:"4 h ago" },
    ]},
];

// Expose
window.OUTCOMES = OUTCOMES;
window.GATE_CRITERIA = GATE_CRITERIA;
window.POLICY_FLOORS = POLICY_FLOORS;
window.COMPLIANCE_MATRIX = COMPLIANCE_MATRIX;
window.GUARDRAILS = GUARDRAILS;
window.STORY_THEMES = STORY_THEMES;
window.BENEFIT_CHAINS = BENEFIT_CHAINS;
window.FLEET = FLEET;

})();
