'use strict';
// platform-init.js — Install skills-platform files into a target repository.
//
// Usage:
//   node scripts/platform-init.js [target-dir] [--force]
//
// Environment:
//   PLATFORM_ROOT              — override the source platform root (default: repo root)
//   PLATFORM_INIT_FAIL_IF_MISSING — if set, exit 1 when target dir cannot be created

const fs = require('fs');
const path = require('path');

// ── Argument parsing ──────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const forceFlag = args.includes('--force');
const positional = args.filter(a => !a.startsWith('-'));
const targetDir = positional[0] ? path.resolve(positional[0]) : process.cwd();

// ── Source root ───────────────────────────────────────────────────────────────
const sourceRoot = process.env.PLATFORM_ROOT
  ? path.resolve(process.env.PLATFORM_ROOT)
  : path.join(__dirname, '..');

// ── Directories to copy ───────────────────────────────────────────────────────
const COPY_DIRS = [
  { src: path.join(sourceRoot, '.github', 'skills'), dest: path.join(targetDir, '.github', 'skills') },
  { src: path.join(sourceRoot, '.github', 'templates'), dest: path.join(targetDir, '.github', 'templates') },
  { src: path.join(sourceRoot, 'scripts'), dest: path.join(targetDir, 'scripts') }
];

const COPILOT_INSTRUCTIONS_DEST = path.join(targetDir, '.github', 'copilot-instructions.md');

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Recursively list all files under a directory, returning absolute paths. */
function listFiles(dir) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir)) {
    const full = path.join(dir, entry);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) {
      results.push(...listFiles(full));
    } else {
      results.push(full);
    }
  }
  return results;
}

/** Copy a single file from src to dest. Returns 'copied' | 'skipped'. */
function copyFile(src, dest, force) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  if (!force && fs.existsSync(dest)) return 'skipped';
  fs.copyFileSync(src, dest);
  return 'copied';
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
  // Validate / create target
  if (process.env.PLATFORM_INIT_FAIL_IF_MISSING === '1' && !fs.existsSync(targetDir)) {
    process.stderr.write(
      `[platform-init] Cannot create target directory: ${targetDir}\n` +
      `[platform-init] Directory does not exist and PLATFORM_INIT_FAIL_IF_MISSING is set.\n`
    );
    process.exit(1);
  }

  try {
    fs.mkdirSync(targetDir, { recursive: true });
  } catch (err) {
    process.stderr.write(
      `[platform-init] Failed to create target directory '${targetDir}': ${err.message}\n`
    );
    process.exit(1);
  }

  const installed = [];
  const skipped = [];

  // Copy platform directories
  for (const { src, dest } of COPY_DIRS) {
    for (const srcFile of listFiles(src)) {
      const relative = path.relative(src, srcFile);
      const destFile = path.join(dest, relative);
      const result = copyFile(srcFile, destFile, forceFlag);
      if (result === 'copied') installed.push(path.relative(targetDir, destFile));
      else skipped.push(path.relative(targetDir, destFile));
    }
  }

  // Create .github/copilot-instructions.md
  const ciDest = COPILOT_INSTRUCTIONS_DEST;
  if (!forceFlag && fs.existsSync(ciDest)) {
    skipped.push(path.relative(targetDir, ciDest));
  } else {
    fs.mkdirSync(path.dirname(ciDest), { recursive: true });
    const ciContent = [
      '# Copilot Instructions',
      '',
      '<!-- Generated by platform:init — customise after installation. -->',
      '',
      '## Active context',
      '',
      'Active pipeline context: `.github/context.yml`',
      '',
      '## Next step',
      '',
      'Run `/orient` to find out where you are in the delivery pipeline and which skill to run next.',
      ''
    ].join('\n');
    fs.writeFileSync(ciDest, ciContent, 'utf8');
    installed.push(path.relative(targetDir, ciDest));
  }

  // Output summary
  if (installed.length > 0) {
    console.log(`[platform-init] Installed ${installed.length} file(s):`);
    for (const f of installed) console.log(`  + ${f}`);
  }
  if (skipped.length > 0) {
    console.log(`[platform-init] Skipped ${skipped.length} existing file(s) (use --force to overwrite):`);
    for (const f of skipped) console.log(`  ~ ${f}`);
  }
  if (installed.length === 0 && skipped.length === 0) {
    console.log('[platform-init] Nothing to install.');
  }
  console.log('[platform-init] Done.');
}

main();
